theme: jekyll-theme-minimal
title: Julianna Huerta
logo: ![PicsArt_11-08-11.23.36] 
description: Hi, my name is Julianna Huerta. I am an Illustrator and a Game Concept Artist. I am making this portfolio in case I want to work with coding in the future for a game company. 
