theme: jekyll-theme-minimal
title: Julianna Huerta
logo: file:///C:/Users/julia/OneDrive/Desktop/PicsArt_11-08-11.23.36.png
description: Hi, my name is Julianna Huerta. I am an Illustrator and a Game Concept Artist. I am making this portfolio in case I want to work with coding in the future for a game company. 
